apiVersion: v1
data:
  {{ arg_opts['application'] }}-django-admin-token: {{ arg_opts['admin_token'] }}
  {{ arg_opts['application'] }}-django-admin-password: {{ arg_opts['admin_password'] }}
  {{ arg_opts['application'] }}-django-secret-key: {{ arg_opts['secret_key'] }}
  {{ arg_opts['application'] }}-database-password: {{ arg_opts['database_password'] }}
  {{ arg_opts['application'] }}-readonly-db-password: {{ arg_opts['readonly_db_password'] }}
kind: Secret
metadata:
  annotations:
  name: {{ arg_opts['application'] }}-secrets
  namespace: {{ arg_opts['project'] }}
type: Opaque
