apiVersion: v1
data:
  {{ app }}-django-admin-token: {{ arg_opts['admin_token'] }}
  {{ app }}-django-admin-password: {{ arg_opts['admin_password'] }}
  {{ app }}-django-secret-key: {{ arg_opts['secret_key'] }}
  {{ app }}-database-password: {{ arg_opts['database_password'] }}
  {{ app }}-readonly-db-password: {{ arg_opts['readonly_db_password'] }}
{% if app == 'couchdb-sync' %}
  {{ app }}-google-client-id: {{ arg_opts['google_client_id'] }}
{% endif %}
kind: Secret
metadata:
  annotations:
  name: {{ app }}-secrets
  namespace: {{ arg_opts['project'] }}
type: Opaque
