version: "2.1"

networks:
  aether:
    external:
      name: aether_bootstrap_net

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-log:

services:

  # ---------------------------------
  # Kafka & Zookeeper
  # ---------------------------------

  zookeeper:
    extends:
      file: ./docker-compose-base.yml
      service: zookeeper-base
    restart: on-failure
    networks:
      - aether
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}
      - moby:127.0.0.1

  kafka:
    extends:
      file: ./docker-compose-base.yml
      service: kafka-base
    restart: always
    depends_on:
      - zookeeper
    networks:
      - aether
    volumes:
      - kafka-data:/var/lib/kafka/data
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}
      - moby:127.0.0.1

  # ---------------------------------
  # Aether Kafka Producer
  # ---------------------------------

  producer:
    extends:
      file: ./docker-compose-base.yml
      service: aether-producer-base
    restart: on-failure
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}
