version: '3.7'

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:

  stream-consumer:
    image: ehealthafrica/aether-stream-consumer:0.3.0
    environment:
      # consumer settings
      CONSUMER_NAME: 'STREAM'

      # redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: 0
      REDIS_HOST: redis-stream-consumer
      REDIS_PORT: 6379
      
      # kafka
      KAFKA_CONFIG_PATH: /code/conf/consumer/kafka.json
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: ${KAFKA_SECURITY}
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_CONSUMER_USER}
      SASL.PASSWORD: ${KAFKA_CONSUMER_PASSWORD}
      EXPOSE_PORT: 9013
    depends_on:
      - redis-stream-consumer
    command: start
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}


  redis-stream-consumer:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - aether

  zeebe_ingress:
    container_name: zeebe_ingress
    image: nginx:latest
    environment:
      ZEEBE_REALM: ${ZEEBE_REALM}
    volumes:
      - ./conf/nginx.template:/etc/nginx/templates/nginx.template
      # - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "26500:26500"    # authenticated zb port
      # - "26507:26507"  # public zeebe port
      - "9600:9600"      # HC / metrics 
    networks:
      - aether

  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.24.1
    environment:
      - ZEEBE_LOG_LEVEL=debug
    volumes:
      - ./lib/zeebe-hazelcast-exporter-0.9.0-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./conf/application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - aether

  zeebe_monitor:
    container_name: zeebe-simple-monitor
    image: ehealthafrica/zeebe-simple-monitor:0.19.1
    environment:
      zeebe.client.broker.contactPoint: zeebe:26500
      zeebe.client.worker.hazelcast.connection: zeebe:5701
      server.context-path: /${ZEEBE_REALM}/zb_monitor/
    volumes:
      - ./lib/zeebe-hazelcast-exporter-0.9.0-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
    # ports:  # for debugging only
    #   - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - aether
     extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}
