networks:
  aether:
    name: aether_bootstrap_net
    external: true

volumes:
  theme_ehealth:

services:

  # ---------------------------------
  # Gateway Service
  # ---------------------------------

  kong:
    image: ehealthafrica/kong:${KONG_VERSION:-latest}
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}

      KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: 16 128k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 16 128k
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 128k
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:80, ssl 0.0.0.0:443

      KONG_PLUGINS: bundled,kong-oidc-auth

      KONG_LOG_LEVEL: error
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - 80:80
      - 443:443
      # - 8001:8001  # open this port to access to kong admin
    command: ['kong', 'start', '--v']
    networks:
      aether:
        ipv4_address: ${KONG_IP}
    extra_hosts:
      - ${BASE_DOMAIN}:127.0.0.1

  # ---------------------------------
  # Gateway Authentication
  # ---------------------------------

  keycloak-eha-themes:
    image: ehealthafrica/keycloak-themes:${KEYCLOAK_THEMES_VERSION:-latest}
    volumes:
      - theme_ehealth:/var/tmp/ehealth:rw
    command: ["sh", "-c", "cp -R ./themes/ehealth-theme/* /var/tmp/ehealth"]

  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION:-latest}
    volumes:
      # custom ehealth theme
      - theme_ehealth:/opt/jboss/keycloak/themes/ehealth:ro
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}

      KEYCLOAK_USER: ${KEYCLOAK_GLOBAL_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD}

      PROXY_ADDRESS_FORWARDING: 'true'
      PROXY_PORT_FORWARDING: 'true'

      KEYCLOAK_LOGLEVEL: ERROR
      ROOT_LOGLEVEL: ERROR
    links:
      - keycloak-eha-themes
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}


  # ---------------------------------
  # Gateway Manager
  # ---------------------------------

  gateway-manager:
    image: ehealthafrica/gateway-manager:${GATEWAY_VERSION:-latest}
    environment:
      DEBUG: null

      BASE_DOMAIN: ${BASE_DOMAIN}
      BASE_HOST: ${BASE_PROTOCOL}://${BASE_DOMAIN}

      KEYCLOAK_GLOBAL_ADMIN: ${KEYCLOAK_GLOBAL_ADMIN}
      KEYCLOAK_GLOBAL_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD}

      KEYCLOAK_INTERNAL: ${KEYCLOAK_INTERNAL}/
      KONG_INTERNAL: ${KONG_INTERNAL}

      ZOOKEEPER_HOST: zookeeper:32181
      ZOOKEEPER_USER: ${ZOOKEEPER_ROOT_USER}
      ZOOKEEPER_PW: ${ZOOKEEPER_ROOT_PASSWORD}
      KAFKA_SECRET: ${KAFKA_SECRET}

      CC_API_USER: ${CC_API_USER}
      CC_API_PASSWORD: ${CC_API_PASSWORD}
      CC_CLUSTER_NAME: ${CC_CLUSTER_NAME}

      ELASTICSEARCH_HOST: http://elasticsearch:9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PW: ${ELASTICSEARCH_PASSWORD}

      CDN_URL: ${BASE_PROTOCOL}://${BASE_DOMAIN}/gateway

      WEB_SERVER_PORT: 8007
    volumes:
      - ./app:/code/app
      - ./service:/code/service
      - ./solution:/code/solution
      - ./data/services.json:/code/data/services.json
    command: start_app
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}


  #---------------------------------
  # Konga
  # https://github.com/pantsel/konga
  # Accessible in http://localhost:1337
  #---------------------------------

  konga:
    image: pantsel/konga:latest
    environment:
      DB_ADAPTER: postgres
      DB_HOST: db
      DB_PORT: '5432'
      DB_DATABASE: konga
      DB_USER: konga
      DB_PASSWORD: ${KONGA_PG_PASSWORD}
      NODE_ENV: production
      KONGA_HOOK_TIMEOUT: 120000
    depends_on:
      - kong
    ports:
      - 1337:1337
    networks:
      - aether
