version: "2.1"

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:

  odfe-elasticsearch:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch-open-base
    environment:
      opendistro_security.ssl.http.enabled: "false"
    networks:
      - aether

  odfe-kibana:
    extends:
      file: docker-compose-base.yml
      service: kibana-open-base
    depends_on:
      - odfe-elasticsearch
    environment:
      ELASTICSEARCH_URL: http://odfe-elasticsearch:9200
      opendistro_security.ssl.http.enabled: "false"
    networks:
      - aether

  # elasticsearch-consumer:
  #   extends:
  #     file: docker-compose-base.yml
  #     service: es-consumer-base
  #   environment:
  #     ELASTICSEARCH_INSTANCE_URLS: "elasticsearch"
  #     BOOTSTRAP_SERVERS: "kafka:29092"
  #     CONSUMER_PORT: 9099
  #     ES_CONSUMER_CONFIG_PATH: "/code/conf/consumer/consumer.json"
  #     ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/conf/consumer/kafka.json"
  #   links:
  #     - elasticsearch
  #   networks:
  #     - aether
