networks:
  aether:
    name: aether_bootstrap_net
    external: true

services:

  # ---------------------------------
  # Data Generation
  # ---------------------------------

  assets:
    image: aether-assets
    build: ./generation
    volumes:
      - ./generation:/code
      - ./resources:/code/resources
    environment:
      KERNEL_URL: ${BASE_PROTOCOL}://${BASE_DOMAIN}/dev/kernel
      KERNEL_USER: ${INITIAL_USER_USERNAME}
      KERNEL_PASSWORD: ${INITIAL_USER_PASSWORD}

      REALM: dev
      KEYCLOAK_URL: ${BASE_PROTOCOL}://${BASE_DOMAIN}/auth

      CLIENT_LOGLEVEL: INFO
      ROOT_LOGLEVEL: DEBUG

      PROJECT_NAME: DefaultDemo
      MAPPING_NAME: default_mapping

      PYTHONPYCACHEPREFIX: "/var/tmp/cache/cpython/"
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}
