version: "2.1"

services:

# ---------------------------------
  # Gather
  # ---------------------------------

  gather-base:
    image: ehealthafrica/gather:${GATHER_VERSION:-latest}
    stdin_open: true
    tty: true
    environment:
      CSRF_COOKIE_DOMAIN: ${BASE_DOMAIN}
      DJANGO_SECRET_KEY: ${GATHER_DJANGO_SECRET_KEY}
      LOGGING_FORMATTER: verbose

      APP_NAME: Gather

      MULTITENANCY: "true"
      DEFAULT_REALM: ${DEFAULT_REALM}
      REALM_COOKIE: ${REALM_COOKIE}

      ADMIN_USERNAME: ${GATHER_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${GATHER_ADMIN_PASSWORD}

      EXTERNAL_APPS: aether-kernel,aether-odk

      AETHER_KERNEL_TOKEN: ${KERNEL_ADMIN_TOKEN}
      AETHER_KERNEL_URL: ${BASE_HOST}/${PUBLIC_REALM}/kernel/

      AETHER_ODK_TOKEN: ${ODK_ADMIN_TOKEN}
      AETHER_ODK_URL: ${BASE_HOST}/${PUBLIC_REALM}/odk/

      DB_NAME: gather
      PGHOST: db # This matches the DB service name
      PGPASSWORD: ${GATHER_DB_PASSWORD}
      PGPORT: 5432
      PGUSER: postgres

      EXPORT_MAX_ROWS_SIZE: 2500

      # Kong requirements
      GATEWAY_SERVICE_ID: gather
      GATEWAY_PUBLIC_REALM: ${PUBLIC_REALM}

      KEYCLOAK_SERVER_URL: ${BASE_HOST}/keycloak/auth/realms
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_GATHER_CLIENT}

      UWSGI_BUFFER_SIZE: 32768
      CUSTOM_UWSGI_SERVE_STATIC: "true"

      WEB_SERVER_PORT: 8105

      # Use this value with "HMR" otherwise you can comment it out
      WEBPACK_STATS_FILE: /code/gather/assets/bundles/webpack-stats.json
    volumes:
      - ../.persistent_data/backups/gather:/backups
      - ../.persistent_data/static/gather:/var/www/static
    ports:
      - 8105:8105
    command: start