version: "2.1"

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:

  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: ./docker-compose-base.yml
      service: gather-base
    # depends_on:
    #   db:
    #     condition: service_healthy
    networks:
      aether:
        aliases:
          - aether.local