version: '3'

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:

  # ---------------------------------
  # Aether ODK Module
  # ---------------------------------

  odk:
    image: ehealthafrica/aether-odk:${AETHER_VERSION:-alpha}
    environment:
      CSRF_COOKIE_DOMAIN: ${BASE_DOMAIN}
      DJANGO_SECRET_KEY: ${ODK_DJANGO_SECRET_KEY}
      LOGGING_FORMATTER: verbose
      HTML_SELECT_CUTOFF: 10
      PROFILING_ENABLED: 'true'

      BUCKET_NAME: odk
      DJANGO_STORAGE_BACKEND: minio
      MINIO_STORAGE_ACCESS_KEY: ${MINIO_STORAGE_ACCESS_KEY}
      MINIO_STORAGE_SECRET_KEY: ${MINIO_STORAGE_SECRET_KEY}
      MINIO_STORAGE_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_STORAGE_MEDIA_USE_PRESIGNED: null
      MINIO_STORAGE_MEDIA_URL: http://${MINIO_ENDPOINT}/odk
      MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET: 'true'
      MINIO_STORAGE_AUTO_CREATE_MEDIA_POLICY: 'true'

      APP_NAME: Aether ODK

      ADMIN_USERNAME: ${ODK_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ODK_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${ODK_ADMIN_TOKEN}

      AETHER_KERNEL_TOKEN: ${KERNEL_ADMIN_TOKEN}
      AETHER_KERNEL_URL: ${BASE_PROTOCOL}://${BASE_DOMAIN}/{realm}/kernel

      DB_NAME: odk
      PGHOST: db
      PGPASSWORD: ${ODK_DB_PASSWORD}
      PGPORT: 5432
      PGUSER: odk

      # Kong requirements
      GATEWAY_SERVICE_ID: odk
      GATEWAY_PUBLIC_REALM: ${PUBLIC_REALM}

      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_AETHER_CLIENT}

      MULTITENANCY: 'true'
      DEFAULT_REALM: ${DEFAULT_REALM}
      REALM_COOKIE: ${REALM_COOKIE}

      UWSGI_BUFFER_SIZE: 32768
      CUSTOM_UWSGI_SERVE_STATIC: 'true'

      WEB_SERVER_PORT: 8002
    volumes:
      # backup folder
      - ../.persistent_data/backups/odk:/backups
    command: start
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}


  # ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    image: ehealthafrica/gather:${GATHER_VERSION:-alpha}
    environment:
      CSRF_COOKIE_DOMAIN: ${BASE_DOMAIN}
      DJANGO_SECRET_KEY: ${GATHER_DJANGO_SECRET_KEY}
      LOGGING_FORMATTER: verbose
      PROFILING_ENABLED: 'true'

      APP_NAME: Gather

      ADMIN_USERNAME: ${GATHER_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${GATHER_ADMIN_PASSWORD}

      EXTERNAL_APPS: aether-kernel,aether-odk

      AETHER_KERNEL_TOKEN: ${KERNEL_ADMIN_TOKEN}
      AETHER_KERNEL_URL: ${BASE_PROTOCOL}://${BASE_DOMAIN}/{realm}/kernel

      AETHER_ODK_TOKEN: ${ODK_ADMIN_TOKEN}
      AETHER_ODK_URL: ${BASE_PROTOCOL}://${BASE_DOMAIN}/{realm}/odk

      DB_NAME: gather
      PGHOST: db # This matches the DB service name
      PGPASSWORD: ${GATHER_DB_PASSWORD}
      PGPORT: 5432
      PGUSER: gather

      EXPORT_MAX_ROWS_SIZE: 2500

      # Kong requirements
      GATEWAY_SERVICE_ID: gather
      GATEWAY_PUBLIC_REALM: ${PUBLIC_REALM}

      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_AETHER_CLIENT}

      MULTITENANCY: 'true'
      DEFAULT_REALM: ${DEFAULT_REALM}
      REALM_COOKIE: ${REALM_COOKIE}

      UWSGI_BUFFER_SIZE: 32768
      CUSTOM_UWSGI_SERVE_STATIC: 'true'

      WEB_SERVER_PORT: 8105
    command: start
    networks:
      - aether
    extra_hosts:
      - ${BASE_DOMAIN}:${KONG_IP}
