name: Tests

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:

  test-setup:
    name: Test setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add hosts to /etc/hosts
        run: sudo echo "127.0.0.1 aether.test.server" | sudo tee -a /etc/hosts
      - name: Set up
        run: |
          export TERM=xterm
          ./scripts/tests.sh setup

  test-integration:
    name: Integration tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add hosts to /etc/hosts
        run: sudo echo "127.0.0.1 aether.test.server" | sudo tee -a /etc/hosts
      - name: Integration tests
        run: |
          export TERM=xterm
          ./scripts/tests.sh integration
