version: "2.1"
services:
  elasticsearch-base:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  kibana-base:
    image: amazon/opendistro-for-elasticsearch-kibana:0.9.0
    ports:
      - "5601:5601"
    environment:
      kibana.index: "aether-demo-2"

  es-consumer-base:
    image: ehealthafrica/aether-elasticsearch-consumer:1.1.2
    stdin_open: true
    ports:
      - "9009:9009"
    volumes:
     - ./conf:/code/conf/consumer
     - ./es_index:/code/es_index

    environment:
     - PYTHONUNBUFFERED=0
    command: start

