version: "2.1"

networks:
  aether:
    external:
      name: aether_bootstrap_net

volumes:
  # docker volume create storage for es data	
  elastic_data:
    external:
      name: odfe_data

services:

  odfe-es:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch-base
    networks:
      - aether
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
            - opendistro_security.ssl.http.enabled=false      
  odfe-kibana:
    extends:
      file: docker-compose-base.yml
      service: kibana-base
    depends_on:
      - odfe-es
    networks:
      - aether
    environment:
      ELASTICSEARCH_URL: http://odfe-es:9200
      ELASTICSEARCH_HOSTS: http://odfe-es:9200

  odfe-es-consumer:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    environment:
      ELASTICSEARCH_INSTANCE_URLS: "admin:admin@odfe-es"
      BOOTSTRAP_SERVERS: "admin:admin@kafka:29092"
      CONSUMER_PORT: 9099
      ES_CONSUMER_CONFIG_PATH: "/code/conf/consumer/consumer.json"
      ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/conf/consumer/kafka.json"
    networks:
      - aether
